In [1]:
import numpy as np
import dask.array as da

In [26]:
arr = np.array([[1,2,3]]*10000000)

In [27]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       ...,
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [28]:
%time np.apply_over_axes(sum, arr, 0)

CPU times: user 4.85 s, sys: 17.2 ms, total: 4.87 s
Wall time: 4.86 s


array([[10000000, 20000000, 30000000]])

In [29]:
%time da.apply_over_axes(sum, arr, 0).compute()

CPU times: user 2.09 s, sys: 5.42 ms, total: 2.09 s
Wall time: 2.09 s


array([[10000000, 20000000, 30000000]])

In [45]:
arr.shape, int(np.ceil(arr.shape[0]/10)), int(np.ceil(arr.shape[1]/10))

((10000000, 3), 1000000, 1)

In [50]:
%time da.from_array(arr, chunks="auto").map_blocks(lambda x:x+1).compute()

CPU times: user 399 ms, sys: 260 ms, total: 659 ms
Wall time: 448 ms


array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       ...,
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [ ]:
da.map_blocks()